package com.genkey.common.modules.registration.modules_registration_biographic_api

import com.genkey.common.modules.registration._modules_registration_domain.Biographics.BasicBiographics


interface BasicBiographicsEditor: Editor<BasicBiographics>
