package com.genkey.common.modules.registration._modules_registration_common.domain

import java.util.*

/*
CREATE TABLE public.centers (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	registered_at timestamptz DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	external_code varchar(255) NOT NULL,
	internal_code varchar(255) NOT NULL,
	center_type varchar(255) NOT NULL,
	center_name varchar(255) NOT NULL,
	display_label varchar(255) NOT NULL,
	description varchar(255) NULL,
	is_active bool DEFAULT true NOT NULL,
	address varchar(255) NULL,
	postal_code varchar(255) NULL,
	gps_latitude float4 NULL,
	gps_longitude float4 NULL,
	demarcation_entry_id int8 NOT NULL,
	CONSTRAINT pk_centers PRIMARY KEY (id),
	CONSTRAINT fk_centers_demarcations_entries FOREIGN KEY (demarcation_entry_id) REFERENCES public.demarcations_entries(id)
);
 */
class Center(
    val id:Int,
    val registeredAt: Date,
    val externalCode: String,
    val internalCode: String,
    val centerType: String,
    val centerName: String,
    val displayLabel: String,
    val description: String? = null,
    val address: Address? = null,
    val gpsLatitude: Float? = null,
    val gpsLongitude: Float? = null,
    val demarcationEntryId: Int
)
{
}